name: Run Tests
##
# This github workflow is used to run tests on all commits to the master branch.
##

on:
  push:
    branches:
      - master

jobs:

  lint:
    name: Lint Checks

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install -y python3-flake8

      - name: Python Lint (flake8)
        run: python3 -m flake8 dcheck

  docs:
    name: Build Docs

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install -y python3-sphinx python3-sphinx-rtd-theme

      - name: Build Documentation
        run: make -C docs html

  tests:
    name: Unit Tests

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install -y python3-pytest python3-tk python3-yaml

      - name: Run Tests
        run: make test

#  release:
#    name: Test Release
#
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      # Test Release
#      - run: make release
